version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.23.0
    ports:
      - 9090:9090/tcp
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml:ro

  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - 9093:9093/tcp
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-storage:/alertmanager
    depends_on:
      - prometheus

  node_exporter:
    image: prom/node-exporter:v1.0.1
    # ports:
    #   - 9100:9100/tcp
    depends_on:
      - prometheus
#    privileged: true
    # https://github.com/prometheus/node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  grafana:
    image: grafana/grafana:7.3.4-ubuntu
    ports:
      - 3000:3000/tcp
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      # not appropriate other than in private network
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"

  timescaledb:
    image: timescale/timescaledb:1.7.4-pg12
    ports:
      - 5432:5432/tcp
    volumes:
      - ~/timescale/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: timescale

  promscale:
    # not available on DockerHub, must be built
    image: timescale/promscale-arml7:0.1.3
    ports:
      - 9201:9201/tcp
    depends_on:
      - timescaledb
    environment:
      TS_PROM_DB_HOST: timescaledb
      TS_PROM_DB_PASSWORD: postgres
      TS_PROM_DB_USER: postgres
      TS_PROM_DB_SSL_MODE: allow
      TS_PROM_LOG_LEVEL: info
      TS_PROM_WEB_TELEMETRY_PATH: /metrics

  atom1:
    image: envii_exporter:latest
    build: .
    ports:
      - 8001:8001/tcp
    environment:
      ENVII_POLL_ADDRESS: http://192.168.11.12:9000
      ENVII_TIMEOUT: 20
      ENVII_LISTEN_ADDRESS: 0.0.0.0:8001

  m5stickc:
    image: envii_exporter:latest
    build: .
    ports:
      - 8002:8002/tcp
    environment:
      ENVII_POLL_ADDRESS: http://192.168.11.35:9000
      ENVII_TIMEOUT: 20
      ENVII_LISTEN_ADDRESS: 0.0.0.0:8002

  atom2:
    image: envii_exporter:latest
    build: .
    ports:
      - 8003:8003/tcp
    environment:
      ENVII_POLL_ADDRESS: http://192.168.11.41:9000
      ENVII_TIMEOUT: 20
      ENVII_LISTEN_ADDRESS: 0.0.0.0:8003

volumes:

  grafana-storage:

  alertmanager-storage:
