global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
    monitor: codelab-monitor
rule_files:
  - /etc/prometheus/prometheus.rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
scrape_configs:
  - job_name: envii
    static_configs:
      - targets:
        - 192.168.11.20:8001
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
        - node_exporter:9100
        labels:
          group: serine
  - job_name: promscale
    static_configs:
      - targets:
        - promscale:9201
remote_write:
  - url: http://promscale:9201/write
remote_read:
  - url: http://promscale:9201/read
